// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: simpletwo.flex

/*
 * Copyright 2020, Gerwin Klein, Régis Décamps, Steve Rowe
 * SPDX-License-Identifier: BSD-3-Clause
 */


@SuppressWarnings("fallthrough")
public class compilerFaz1 {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\0\1\11\1\12\1\13\2\14"+
    "\1\15\1\16\1\14\1\17\1\20\1\21\1\22\1\23"+
    "\6\24\2\25\2\14\1\26\1\27\1\30\2\0\4\31"+
    "\1\32\1\31\24\33\1\0\1\34\1\0\1\35\1\36"+
    "\1\0\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\33\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\33\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\2\33\1\14\1\65\1\14\1\35\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\1\1\11\3\7\2\12\1\13\1\14"+
    "\1\13\1\15\1\10\13\15\1\10\2\16\1\17\1\13"+
    "\1\20\5\0\1\14\1\5\2\0\1\7\1\21\1\22"+
    "\1\0\1\23\3\0\7\15\1\24\2\15\1\24\10\15"+
    "\1\25\3\0\1\26\2\0\1\27\1\30\1\0\1\30"+
    "\1\31\1\32\21\15\6\0\13\15\1\0\1\26\1\0"+
    "\10\15\1\0\4\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\242\0\154\0\154\0\330\0\u010e"+
    "\0\u0144\0\u017a\0\u01b0\0\u01e6\0\154\0\u021c\0\u0252\0\u0288"+
    "\0\u02be\0\u02f4\0\u032a\0\330\0\u0360\0\u0396\0\154\0\u03cc"+
    "\0\u0402\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c"+
    "\0\u05b2\0\u05e8\0\u061e\0\u0654\0\154\0\u068a\0\154\0\154"+
    "\0\u06c0\0\u06f6\0\u072c\0\u0762\0\u0798\0\154\0\154\0\u07ce"+
    "\0\u0804\0\154\0\154\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912"+
    "\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2"+
    "\0\u0af8\0\u0b2e\0\u0b64\0\u0396\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\154\0\u0d4a\0\u0d80\0\u0db6"+
    "\0\u0dec\0\u0e22\0\u0e58\0\154\0\u0e8e\0\u0ec4\0\u0ec4\0\u0912"+
    "\0\u0948\0\u0efa\0\u0f30\0\u0f66\0\u0f9c\0\u0fd2\0\u1008\0\u103e"+
    "\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c\0\u1182\0\u11b8\0\u11ee"+
    "\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc\0\u1332\0\u1368\0\u139e"+
    "\0\u13d4\0\u140a\0\u1440\0\u1476\0\u14ac\0\u14e2\0\u1518\0\u154e"+
    "\0\u1584\0\u15ba\0\u15f0\0\u1626\0\154\0\u165c\0\u1692\0\u16c8"+
    "\0\u16fe\0\u1734\0\u176a\0\u17a0\0\u17d6\0\u180c\0\u1842\0\u1878"+
    "\0\u18ae\0\u18e4\0\u191a";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\2\4\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\12\1\16\1\17\1\3"+
    "\1\20\1\21\3\22\1\23\1\24\1\25\3\26\1\3"+
    "\1\27\1\3\1\26\1\30\1\31\1\32\1\33\1\34"+
    "\2\26\1\35\5\26\1\36\1\37\1\40\1\41\2\26"+
    "\1\42\1\26\1\43\2\44\1\45\2\44\1\45\7\44"+
    "\1\46\50\44\67\0\1\4\2\0\2\4\107\0\1\47"+
    "\36\0\2\10\1\0\2\10\1\0\1\10\1\50\24\10"+
    "\1\51\31\10\42\0\1\52\1\53\3\0\1\54\11\0"+
    "\1\55\33\0\1\56\50\0\1\57\53\0\13\60\1\0"+
    "\20\60\1\61\31\60\16\0\1\62\10\0\1\56\55\0"+
    "\1\62\7\0\1\56\53\0\1\63\3\0\1\64\5\0"+
    "\1\56\56\0\1\65\1\0\3\66\1\22\4\0\1\67"+
    "\5\0\1\70\2\0\1\67\20\0\1\71\21\0\1\65"+
    "\1\0\4\22\4\0\1\67\10\0\1\67\50\0\1\27"+
    "\1\47\65\0\1\47\1\27\57\0\4\26\3\0\3\26"+
    "\2\0\27\26\23\0\4\26\3\0\3\26\2\0\16\26"+
    "\1\72\1\26\1\73\6\26\23\0\4\26\3\0\3\26"+
    "\2\0\1\26\1\74\6\26\1\75\2\26\1\76\2\26"+
    "\1\77\10\26\23\0\4\26\3\0\3\26\2\0\5\26"+
    "\1\100\10\26\1\101\10\26\23\0\4\26\3\0\3\26"+
    "\2\0\13\26\1\74\13\26\23\0\4\26\3\0\3\26"+
    "\2\0\13\26\1\102\2\26\1\103\10\26\23\0\4\26"+
    "\3\0\3\26\2\0\6\26\1\104\6\26\1\105\11\26"+
    "\23\0\4\26\3\0\3\26\2\0\20\26\1\106\2\26"+
    "\1\107\3\26\23\0\4\26\3\0\3\26\2\0\5\26"+
    "\1\110\21\26\23\0\4\26\3\0\3\26\2\0\22\26"+
    "\1\111\2\26\1\112\1\26\23\0\4\26\3\0\3\26"+
    "\2\0\5\26\1\113\21\26\23\0\4\26\3\0\3\26"+
    "\2\0\10\26\1\114\16\26\66\0\1\57\2\44\1\0"+
    "\2\44\1\0\7\44\1\0\50\44\21\0\1\115\53\0"+
    "\1\10\3\0\1\10\20\0\1\10\3\0\1\10\3\0"+
    "\1\10\6\0\1\10\2\0\1\10\1\0\1\10\50\0"+
    "\1\116\73\0\1\117\1\0\1\120\56\0\1\121\6\0"+
    "\1\122\65\0\1\123\25\0\1\124\52\0\2\60\4\0"+
    "\60\60\2\64\4\0\60\64\22\0\4\125\60\0\1\65"+
    "\1\0\3\66\1\22\4\0\1\67\10\0\1\67\40\0"+
    "\2\126\2\0\4\127\62\0\2\130\64\0\4\131\3\0"+
    "\2\131\4\0\6\131\43\0\4\26\3\0\3\26\2\0"+
    "\16\26\1\132\10\26\23\0\4\26\3\0\3\26\2\0"+
    "\5\26\1\133\21\26\23\0\4\26\3\0\3\26\2\0"+
    "\21\26\1\134\5\26\23\0\4\26\3\0\3\26\2\0"+
    "\1\26\1\103\25\26\23\0\4\26\3\0\3\26\2\0"+
    "\1\26\1\135\25\26\23\0\4\26\3\0\3\26\2\0"+
    "\15\26\1\136\11\26\23\0\4\26\3\0\3\26\2\0"+
    "\6\26\1\137\20\26\23\0\4\26\3\0\3\26\2\0"+
    "\23\26\1\140\3\26\23\0\4\26\3\0\3\26\2\0"+
    "\16\26\1\141\10\26\23\0\4\26\3\0\3\26\2\0"+
    "\20\26\1\104\6\26\23\0\4\26\3\0\3\26\2\0"+
    "\22\26\1\104\4\26\23\0\4\26\3\0\3\26\2\0"+
    "\11\26\1\142\4\26\1\143\10\26\23\0\4\26\3\0"+
    "\3\26\2\0\2\26\1\144\24\26\23\0\4\26\3\0"+
    "\3\26\2\0\22\26\1\145\4\26\23\0\4\26\3\0"+
    "\3\26\2\0\1\26\1\146\16\26\1\147\6\26\23\0"+
    "\4\26\3\0\3\26\2\0\11\26\1\150\15\26\23\0"+
    "\4\26\3\0\3\26\2\0\14\26\1\151\12\26\23\0"+
    "\4\26\3\0\3\26\2\0\11\26\1\152\15\26\45\0"+
    "\1\153\70\0\1\154\7\0\1\155\50\0\1\156\65\0"+
    "\1\157\10\0\1\123\53\0\1\160\66\0\1\157\45\0"+
    "\4\125\4\0\1\67\10\0\1\67\44\0\4\127\62\0"+
    "\4\26\3\0\3\26\2\0\13\26\1\104\13\26\23\0"+
    "\4\26\3\0\3\26\2\0\1\26\1\161\25\26\23\0"+
    "\4\26\3\0\3\26\2\0\5\26\1\104\21\26\23\0"+
    "\4\26\3\0\3\26\2\0\21\26\1\162\5\26\23\0"+
    "\4\26\3\0\3\26\2\0\21\26\1\105\1\163\4\26"+
    "\23\0\4\26\3\0\3\26\2\0\1\26\1\164\25\26"+
    "\23\0\4\26\3\0\3\26\2\0\2\26\1\152\24\26"+
    "\23\0\4\26\3\0\3\26\2\0\1\26\1\105\25\26"+
    "\23\0\4\26\3\0\3\26\2\0\24\26\1\165\2\26"+
    "\23\0\4\26\3\0\3\26\2\0\22\26\1\166\4\26"+
    "\23\0\4\26\3\0\3\26\2\0\13\26\1\167\13\26"+
    "\23\0\4\26\3\0\3\26\2\0\23\26\1\170\3\26"+
    "\23\0\4\26\3\0\3\26\2\0\22\26\1\167\4\26"+
    "\23\0\4\26\3\0\3\26\2\0\11\26\1\171\15\26"+
    "\23\0\4\26\3\0\3\26\2\0\22\26\1\172\4\26"+
    "\23\0\4\26\3\0\3\26\2\0\17\26\1\173\7\26"+
    "\23\0\4\26\3\0\3\26\2\0\13\26\1\134\13\26"+
    "\50\0\1\174\62\0\1\175\64\0\1\175\71\0\1\154"+
    "\61\0\1\154\73\0\1\176\36\0\4\26\3\0\3\26"+
    "\2\0\12\26\1\104\14\26\23\0\4\26\3\0\3\26"+
    "\2\0\21\26\1\104\5\26\23\0\4\26\3\0\3\26"+
    "\2\0\11\26\1\177\15\26\23\0\4\26\3\0\3\26"+
    "\2\0\23\26\1\200\3\26\23\0\4\26\3\0\3\26"+
    "\2\0\1\26\1\201\25\26\23\0\4\26\3\0\3\26"+
    "\2\0\5\26\1\202\21\26\23\0\4\26\3\0\3\26"+
    "\2\0\11\26\1\203\15\26\23\0\4\26\3\0\3\26"+
    "\2\0\20\26\1\204\6\26\23\0\4\26\3\0\3\26"+
    "\2\0\15\26\1\205\11\26\23\0\4\26\3\0\3\26"+
    "\2\0\3\26\1\206\23\26\23\0\4\26\3\0\3\26"+
    "\2\0\13\26\1\165\13\26\54\0\1\155\73\0\1\207"+
    "\26\0\4\26\3\0\3\26\2\0\15\26\1\210\11\26"+
    "\23\0\4\26\3\0\3\26\2\0\13\26\1\105\13\26"+
    "\23\0\4\26\3\0\3\26\2\0\22\26\1\134\4\26"+
    "\23\0\4\26\3\0\3\26\2\0\3\26\1\211\23\26"+
    "\23\0\4\26\3\0\3\26\2\0\3\26\1\104\23\26"+
    "\23\0\4\26\3\0\3\26\2\0\15\26\1\104\11\26"+
    "\23\0\4\26\3\0\3\26\2\0\7\26\1\104\17\26"+
    "\23\0\4\26\3\0\3\26\2\0\10\26\1\104\16\26"+
    "\43\0\1\155\45\0\4\26\3\0\3\26\2\0\23\26"+
    "\1\134\3\26\23\0\4\26\3\0\3\26\2\0\22\26"+
    "\1\212\4\26\23\0\4\26\3\0\3\26\2\0\5\26"+
    "\1\213\21\26\23\0\4\26\3\0\3\26\2\0\4\26"+
    "\1\104\22\26\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6480];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\2\11\6\1\1\11\11\1\1\11"+
    "\15\1\1\11\1\1\2\11\5\0\2\11\2\0\2\11"+
    "\1\1\1\0\1\1\3\0\23\1\1\11\3\0\1\1"+
    "\2\0\1\11\1\1\1\0\24\1\6\0\13\1\1\0"+
    "\1\11\1\0\10\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[139];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  private StringBuilder multiLineComment = new StringBuilder();
  private long commentStartLine = 0;
  private long commentStartColumn = 0;
  private long lineStartChar = 0;



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public compilerFaz1(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Illegal character: <" + yytext() + "> - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 27: break;
          case 2:
            { 
            }
          // fall through
          case 28: break;
          case 3:
            { lineStartChar = yychar + 1;
            }
          // fall through
          case 29: break;
          case 4:
            { System.out.print(yytext());
            }
          // fall through
          case 30: break;
          case 5:
            { System.out.println("Logical Operator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 31: break;
          case 6:
            { System.out.println("Unterminated String (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 32: break;
          case 7:
            { System.out.println("Arithmetic Operator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 33: break;
          case 8:
            { System.out.println("Bit Operator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 34: break;
          case 9:
            { System.out.println("Separator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 35: break;
          case 10:
            { System.out.println("Integer Literal (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 36: break;
          case 11:
            { System.out.println("Comparison Operator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 37: break;
          case 12:
            { System.out.println("Assignment Operator (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 38: break;
          case 13:
            { System.out.println("Identifier (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 39: break;
          case 14:
            { multiLineComment.append(yytext());
            }
          // fall through
          case 40: break;
          case 15:
            { multiLineComment.append("*");
            }
          // fall through
          case 41: break;
          case 16:
            { System.out.println("String (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 42: break;
          case 17:
            { yybegin(COMMENT);
    multiLineComment.setLength(0);
    multiLineComment.append("/*");
    commentStartLine = yyline + 1;
    commentStartColumn = (yychar - lineStartChar + 1);
            }
          // fall through
          case 43: break;
          case 18:
            { System.out.println("Single Line Comment (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 44: break;
          case 19:
            { System.out.println("Octal Literal (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 45: break;
          case 20:
            { System.out.println("Keyword (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 46: break;
          case 21:
            { multiLineComment.append("*/");
    System.out.println("Multi Line Comment (" + multiLineComment.toString() + ") - Line " + commentStartLine + ", Column " + commentStartColumn);
    yybegin(YYINITIAL);
            }
          // fall through
          case 47: break;
          case 22:
            { System.out.println("Preprocessor Directive (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1) );
            }
          // fall through
          case 48: break;
          case 23:
            { System.out.println("Character (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 49: break;
          case 24:
            { System.out.println("Float Literal (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 50: break;
          case 25:
            { System.out.println("Binary Literal (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 51: break;
          case 26:
            { System.out.println("Hexadecimal Literal (" + yytext() + ") - Line " + (yyline + 1) + ", Column " + (yycolumn + 1));
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java compilerFaz1 [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        compilerFaz1 scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new compilerFaz1(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
