
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 9;
  public static final int IDENTIFIER = 103;
  public static final int ANDEQ = 95;
  public static final int GT = 75;
  public static final int IMPLEMENTS = 41;
  public static final int CONST = 106;
  public static final int INT_LITERAL = 6;
  public static final int STRICTFP = 105;
  public static final int NOTEQ = 80;
  public static final int PLUSEQ = 90;
  public static final int RBRACK = 16;
  public static final int CATCH = 60;
  public static final int COMMA = 20;
  public static final int RBRACE = 22;
  public static final int THROW = 58;
  public static final int RPAREN = 25;
  public static final int LBRACK = 15;
  public static final int LT = 74;
  public static final int ANDAND = 84;
  public static final int OROR = 85;
  public static final int DOUBLE = 14;
  public static final int LBRACE = 21;
  public static final int TRANSIENT = 37;
  public static final int LPAREN = 24;
  public static final int XOREQ = 96;
  public static final int PROTECTED = 30;
  public static final int INTEGER_LITERAL = 98;
  public static final int NOT = 68;
  public static final int FINAL = 34;
  public static final int FLOAT = 13;
  public static final int GOTO = 107;
  public static final int URSHIFTEQ = 94;
  public static final int PACKAGE = 27;
  public static final int COMP = 67;
  public static final int EQ = 23;
  public static final int assignment_statement = 3;
  public static final int BOOLEAN_LITERAL = 100;
  public static final int MOD = 70;
  public static final int CLASS = 39;
  public static final int SUPER = 45;
  public static final int ABSTRACT = 33;
  public static final int NATIVE = 35;
  public static final int LONG = 11;
  public static final int PLUS = 65;
  public static final int QUESTION = 86;
  public static final int WHILE = 53;
  public static final int EXTENDS = 40;
  public static final int INTERFACE = 46;
  public static final int CHAR = 12;
  public static final int BOOLEAN = 7;
  public static final int SWITCH = 49;
  public static final int DO = 52;
  public static final int FOR = 54;
  public static final int RSHIFTEQ = 93;
  public static final int VOID = 42;
  public static final int DIV = 69;
  public static final int PUBLIC = 29;
  public static final int RETURN = 57;
  public static final int MULT = 19;
  public static final int ELSE = 48;
  public static final int TRY = 59;
  public static final int GTEQ = 77;
  public static final int BREAK = 55;
  public static final int DOT = 17;
  public static final int INT = 10;
  public static final int NULL_LITERAL = 104;
  public static final int THROWS = 43;
  public static final int Double_LITERAL = 5;
  public static final int STRING_LITERAL = 102;
  public static final int EQEQ = 79;
  public static final int EOF = 0;
  public static final int SEMICOLON = 18;
  public static final int THIS = 44;
  public static final int DEFAULT = 51;
  public static final int MULTEQ = 87;
  public static final int IMPORT = 28;
  public static final int MINUS = 66;
  public static final int LTEQ = 76;
  public static final int OR = 83;
  public static final int URSHIFT = 73;
  public static final int error = 1;
  public static final int SYNCHRONIZED = 36;
  public static final int DIVEQ = 88;
  public static final int LSHIFTEQ = 92;
  public static final int FINALLY = 61;
  public static final int CONTINUE = 56;
  public static final int INSTANCEOF = 78;
  public static final int IF = 47;
  public static final int MODEQ = 89;
  public static final int MINUSMINUS = 64;
  public static final int COLON = 26;
  public static final int CHARACTER_LITERAL = 101;
  public static final int Float_LITERAL = 4;
  public static final int OREQ = 97;
  public static final int VOLATILE = 38;
  public static final int CASE = 50;
  public static final int PLUSPLUS = 63;
  public static final int NEW = 62;
  public static final int RSHIFT = 72;
  public static final int BYTE = 8;
  public static final int AND = 81;
  public static final int PRIVATE = 31;
  public static final int STATIC = 32;
  public static final int method_invocation_statement = 2;
  public static final int LSHIFT = 71;
  public static final int XOR = 82;
  public static final int FLOATING_POINT_LITERAL = 99;
  public static final int MINUSEQ = 91;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "method_invocation_statement",
  "assignment_statement",
  "Float_LITERAL",
  "Double_LITERAL",
  "INT_LITERAL",
  "BOOLEAN",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "VOID",
  "THROWS",
  "THIS",
  "SUPER",
  "INTERFACE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "THROW",
  "TRY",
  "CATCH",
  "FINALLY",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "INSTANCEOF",
  "EQEQ",
  "NOTEQ",
  "AND",
  "XOR",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "URSHIFTEQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL",
  "STRICTFP",
  "CONST",
  "GOTO"
  };
}

